config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :bank_accounts
  resources :account_transactions

  get "/pages/:page" => "pages#show"

  root 'pages#home'
end

app/models/account_transaction.rb
class AccountTransaction < ApplicationRecord
  belongs_to :bank_account,    class_name: "BankAccount", foreign_key: "bank_account_id"
  belongs_to :transfer_to_bank_account, class_name: "BankAccount", foreign_key: "transfer_to_id", required: false


  TRANSACTION_TYPES = %w(Withdrawal Deposit Transfer)

  validates :bank_account, presence: true
  validates :amount, presence: true, numericality: true
  validates :transaction_type, presence: true, inclusion: { in: TRANSACTION_TYPES }
  validates :transaction_number, presence: true, uniqueness: true

  before_validation :load_defaults

  def load_defaults
    if self.new_record?
      self.transaction_number = SecureRandom.uuid
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :user

  validates :user, presence: true
  validates :account_number, presence: true, uniqueness: true
  validates :balance, presence: true, numericality: true

  has_many :account_transactions, class_name: "AccountTransaction", foreign_key: "bank_account_id", dependent: :destroy
  has_many :transfer_to_transactions, class_name: "AccountTransaction", foreign_key: "transfer_to_id", dependent: :destroy

  def all_transactions
    AccountTransaction.where("bank_account_id = ? OR transfer_to_id = ?", self.id, self.id)
  end

  def user_and_account
    "#{self.user.full_name} - #{self.account_number}"
  end

  def to_s
    account_number
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :first_name
  validates_presence_of :last_name

  has_many :bank_accounts, dependent: :destroy

  def full_name
    "#{first_name.blank? && last_name.blank? ? email : (first_name + ' ' + last_name)}"
  end

  def total_balance
    self.bank_accounts.map(&:balance).inject(0, &:+)
  end
end

app/controllers/account_transactions_controller.rb
class AccountTransactionsController < ApplicationController
  def index
    @account_transactions = AccountTransaction.all
  end

  def new
    @account_transaction = AccountTransaction.new
    @bank_account = params[:bank_account].nil? ? current_user.bank_accounts.first : BankAccount.find(params[:bank_account])
  end

  def create
  	account_transaction_params[:transfer_to_id] = "" if account_transaction_params[:transaction_type].downcase != "transfer"
    @account_transaction = AccountTransaction.new(account_transaction_params)
    
    @bank_account = account_transaction_params[:bank_account_id].nil? ? current_user.bank_accounts.first : BankAccount.find(account_transaction_params[:bank_account_id])

    respond_to do |format|
      if @account_transaction.save
        if ['withdrawal', 'transfer'].include? @account_transaction.transaction_type.downcase
          @account_transaction.bank_account.update!(balance: @account_transaction.bank_account.balance - @account_transaction.amount)
          @account_transaction.transfer_to_bank_account.update!(balance: @account_transaction.transfer_to_bank_account.balance + @account_transaction.amount) if @account_transaction.transaction_type.downcase == 'transfer'
        elsif @account_transaction.transaction_type.downcase == 'deposit'
          @account_transaction.bank_account.update!(balance: @account_transaction.bank_account.balance + @account_transaction.amount)
        end

        format.html { redirect_to user_path(current_user), notice: 'Transaction was successfully saved.' }
        format.json { render :show, status: :created, location: @account_transaction }
      else
        format.html { render :new }
        format.json { render json: @account_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def account_transaction_params
      params.require(:account_transaction).permit!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  
  def index
    @bank_accounts = BankAccount.all
  end

  def show
    @bank_account = BankAccount.find_by_id(params[:id])
  end

  def new
    @bank_account = BankAccount.new
  end

  def create
  	@bank_account = BankAccount.new(bank_account_params)
    
    respond_to do |format|
      if @bank_account.save
        format.html { redirect_to user_path(current_user), notice: 'Bank Account was successfully saved.' }
        format.json { render :show, status: :created, location: @bank_account }
      else
        format.html { render :new }
        format.json { render json: @bank_account.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def bank_account_params
      params.require(:bank_account).permit!
    end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: [:home]
  
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/account_transactions/index.html.erb
<div class="offset-2 col-lg-8">
  <div class="card">
      <div class="card-header card-header-primary">
          <h2 class="card-title">Account Transactions</h2>
      </div>

      <div class="card-body table-responsive">
        <table class="table table-hover">
          <thead class="text-primary">
            <th>Account</th>
            <th>Date Of Transaction</th>
            <th>Transaction Type</th>
            <th>Amount</th>
          </thead>
          <tbody>
            <% @account_transactions.each do |t| %>
              <tr>
                <td><%= t.bank_account.user_and_account %></td>
                <td><%= t.created_at.strftime("%b %d, %Y - %H:%M%P") %></td>
                <td><%= t.transaction_type.downcase != 'transfer' ? t.transaction_type : "Transferred to #{t.transfer_to_bank_account.user.full_name}" %></td>
                <td><%= number_to_currency(t.amount) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
      
  </div>
</div>

app/views/account_transactions/new.html.erb
<div class="offset-2 col-lg-8">
  <div class="card">
      <div class="card-header card-header-warning">
          <h2 class="card-title">Transaction</h2>
          <p class="card-category"><b>Account Number: <%= @bank_account.account_number %></b></p>
      </div>
      
      <div class="card-body">
        <%= form_for @account_transaction, :as => :account_transaction do |f| %>
          <%= f.hidden_field :bank_account_id, value: @bank_account.id %>
          <%= render "shared/error_messages", resource: @account_transaction %>

          <div class="row" style="margin-bottom:15px;">
            <div class="col-sm-6">
              <%= f.label :amount %>
              <%= f.number_field :amount, autocomplete: "Amount", value: number_to_currency(f.object.amount.to_f, delimiter: '', unit: ''), step: :any, :class => "form-control" %>
            </div>
            <div class="col-sm-6">
              <%= f.label :transaction_type %><br/>
              <%= f.collection_select :transaction_type, AccountTransaction::TRANSACTION_TYPES, :to_s, :to_s, {:include_blank => false}, { :class=>'dropdown transaction_type' } %>
            </div>
          </div>

          <div class="row transfer_to_wrapper" style="display:none; margin-bottom:15px;">
            <div class="col-sm-12">
              <%= f.label :transfer_to_id %>
              <%= f.collection_select :transfer_to_id, BankAccount.where.not(id: @bank_account.id), :id, :user_and_account, {:include_blank => false}, { :class=>'dropdown' } %>
            </div>
          </div>

          <div class="row">
            <div class="col-sm-12">
              <%= f.submit "Save", :class => "btn btn-success" %>
            </div>
          </div>
        <% end %>
      </div>

  </div>
</div>

app/views/bank_accounts/index.html.erb
<div class="offset-2 col-lg-8">
  <div class="card">
      <div class="card-header card-header-primary">
          <h2 class="card-title">Bank Accounts</h2>
      </div>

      <div class="card-body table-responsive">
        <table class="table table-hover">
          <thead class="text-primary">
            <th>Name</th>
            <th>Account Number</th>
            <th>Balance</th>
          </thead>
          <tbody>
            <% @bank_accounts.each do |bank_account| %>
              <tr>
                <td><%= link_to bank_account.user.full_name, user_path(bank_account.user_id) %></td>
                <td><%= link_to bank_account.account_number, bank_account_path(bank_account.id) %></td>
                <td><%= number_to_currency(bank_account.balance) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
      
  </div>
</div>

app/views/bank_accounts/new.html.erb
<div class="offset-2 col-lg-8">
  <div class="card">
      <div class="card-header card-header-warning">
          <h2 class="card-title">Bank Account</h2>
      </div>
      
      <div class="card-body">
        <%= form_for @bank_account, :as => :bank_account do |f| %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= render "shared/error_messages", resource: @bank_account %>

          <div class="row" style="margin-bottom:15px;">
            <div class="col-sm-12">
              <%= f.label :account_number %>
              <%= f.text_field :account_number, autocomplete: "Account Number", :class => "form-control" %>
            </div>
          </div>

          <div class="row">
            <div class="col-sm-12">
              <%= f.submit "Save", :class => "btn btn-success" %>
            </div>
          </div>
        <% end %>
      </div>

  </div>
</div>

app/views/bank_accounts/show.html.erb
<div class="offset-2 col-lg-8">
  <div class="card">
      <div class="card-header card-header-primary">
          <h2 class="card-title">Account Number: <%= @bank_account.account_number %></h2>
          <p class="card-category"><%= @bank_account.user.full_name %></p>
      </div>

      <div class="card-body table-responsive">
        <table class="table table-hover">
          <thead class="text-primary">
            <th>Date Of Transaction</th>
            <th>Transaction Type</th>
            <th>Amount</th>
          </thead>
          <tbody>
            <% @bank_account.all_transactions.each do |t| %>
              <tr>
                <td><%= t.created_at.strftime("%b %d, %Y - %H:%M%P") %></td>
                <td><%= t.transaction_type %></td>
                <td><%= number_to_currency(t.amount) %></td>
              </tr>
            <% end %>
            <tr class="text-primary">
              <td></td>
              <td style="text-align:right; font-weight:bold;">Balance:</td>
              <td><%= number_to_currency(@bank_account.balance) %></td>
            </tr>
          </tbody>
        </table>
    </div>
      
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer ">
  <div class="container-fluid">
    <nav class="pull-left">
      <ul>
        <li>
          <%= link_to '<i class="fa fa-github-alt"></i>'.html_safe, "https://github.com/benhall2121" %>
        </li>
        <li>
          <%= link_to '<i class="fa fa-linkedin"></i>'.html_safe, "https://www.linkedin.com/in/benhall2121/" %>
        </li>
        <li>
          <%= link_to '<i class="fa fa-laptop"></i>'.html_safe, "http://www.benerino.com" %>
        </li>
        <li>
          <%= link_to '<i class="fa fa-umbrella"></i>'.html_safe, "https://www.BPSAssetManagement.com" %>
        </li>
      </ul>
    </nav>

    <div class="copyright pull-right">
      &copy; <%= DateTime.now.year %> <%= link_to "Ben Hall", "http://www.benerino.com" %>
    </div>
  </div>
</footer>

app/views/layouts/_menu.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-transparent">
  <div class="container-fluid">
    <div class="navbar-wrapper">
      <%= link_to "DigiSure Test", root_url, :class => "navbar-brand" %>
    </div>

    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Profile', user_path(current_user), :class => 'navbar-link' %>
        </li>
        &nbsp;|&nbsp;
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
        </li>
        &nbsp;|&nbsp;
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        </li>
      <% end %>

    </ul>
  </div>
</nav>
<!-- End Navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DigiSure Test</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" %>
  </head>

<body class="">
  <div class="wrapper">
        
    <div class="main-panel">
      <%= render 'layouts/menu' %>

      <div class="content">
        <div class="container-fluid">
          <%= yield %>
        </div>
      </div>    

      <%= render 'layouts/footer' %>
    </div>
  </div>
</body>


</html>

app/views/pages/home.html.erb
<div class="offset-2 col-lg-8">
  <div class="card">
      <div class="card-header card-header-warning">
          <h2 class="card-title">DigiSure Test - Ben Hall</h2>
      </div>
      
      <div class="card-body">
        <div class="row" style="margin-bottom:15px;">

          <% if user_signed_in? %>
            <div class="col-sm-3" style="text-align:center;">
                <%= link_to 'Your Accounts'.html_safe, user_path(current_user), :class => "btn btn-sm btn-success" %>
            </div>
            <div class="col-sm-3" style="text-align:center;">
                <%= link_to 'All Accounts'.html_safe, bank_accounts_path, :class => "btn btn-sm btn-success" %>
            </div>
            <div class="col-sm-3" style="text-align:center;">
                <%= link_to 'All Transactions'.html_safe, account_transactions_path, :class => "btn btn-sm btn-success" %>
            </div>
            <div class="col-sm-3" style="text-align:center;">
                <%= link_to 'Logout'.html_safe, destroy_user_session_path, method: :delete, :class => "btn btn-sm btn-success" %>
            </div>
          <% else %>
            <div class="col-sm-6" style="text-align:center;">
                <%= link_to 'Sign up'.html_safe, new_user_registration_path, :class => "btn btn-sm btn-success" %>
            </div>
            <div class="col-sm-6" style="text-align:center;">
                <%= link_to 'Login'.html_safe, new_user_session_path, :class => "btn btn-sm btn-success" %>
            </div>
          <% end %>

        </div>  
      </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>Error: </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="offset-2 col-lg-8">
  <div class="card">
      <div class="card-header card-header-primary">
          <h2 class="card-title">Users</h2>
      </div>

      <div class="card-body table-responsive">
        <table class="table table-hover">
          <thead class="text-primary">
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= link_to user.first_name, user_path(user.id) %></td>
                <td><%= link_to user.last_name, user_path(user.id) %></td>
                <td><%= link_to user.email, user_path(user.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
      
  </div>
</div>

app/views/users/show.html.erb
<div class="row">

  <div class="col-md-4">
    <div class="card card-chart">
      <div class="card-header card-header-success card-header-icon">
        <div class="card-icon">
          <i class="fa fa-user"></i>
        </div>
        <div class="pull-right" style="color:black;">
          <%= link_to 'New Bank Account'.html_safe, new_bank_account_path(:user => @user), :class => "btn btn-sm btn-info" %>
        </div>
      </div>
      <div class="card-body">
        <p class="card-category">Total Balance</p>
        <h3 class="card-title"><%= number_to_currency(@user.total_balance) %></h3>
      </div>
      <div class="card-footer">
        <div class="stats">
          <b>Full Name:</b> &nbsp; <%= @user.full_name %>
        </div>
      </div>
    </div>
  </div>

  <div class="col-lg-8">
  	<% @user.bank_accounts.each do |bank_account| %>
    <div class="card" style="margin-bottom:50px;">
      <div class="card-header card-header-primary">
      	<div class="pull-left">
          <h3 class="card-title">Bank Account #: <%= bank_account.account_number %></h3>
        </div>
        <div class="pull-right">
          <%= link_to '<i class="fa fa-plus-circle"></i> New Transaction'.html_safe, new_account_transaction_path(:bank_account => bank_account), :class => "btn btn-sm btn-info" %>
        </div>
      </div>

      <div class="card-body table-responsive">
        <table class="table table-hover">
          <thead class="text-primary">
            <th>Date Of Transaction</th>
            <th>Transaction Type</th>
            <th>Amount</th>
          </thead>
          <tbody>
            <% bank_account.all_transactions.each do |t| %>
              <tr>
                <td><%= t.created_at.strftime("%b %d, %Y - %H:%M%P") %></td>
                <td><%= t.transaction_type.downcase != 'transfer' ? t.transaction_type : "Transferred to #{t.transfer_to_bank_account.user.full_name} from #{t.bank_account.user.full_name}" %></td>
                <td><%= number_to_currency(t.amount) %></td>
              </tr>
            <% end %>
            <tr class="text-primary">
              <td></td>
              <td style="text-align:right; font-weight:bold;">Balance:</td>
              <td><%= number_to_currency(bank_account.balance) %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <% end %>
  </div>
</div>